name: 部署文档

on:
  push:
    branches:
      - main # 当推送到main分支时触发
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      - name: 构建文档
        run: npm run docs:build # 请确保package.json中有此命令

      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist # 构建输出的目录
          branch: gh-pages # 部署到的分支
          clean: true # 清理目标分支上的旧文件
