name: 构建并部署文档

on:
  # 在推送到main分支时触发
  push:
    branches: [main]
  # 允许手动触发工作流
  workflow_dispatch:

# 设置工作流权限
permissions:
  contents: write # 必需：允许工作流写入仓库内容

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 添加环境变量解决crypto问题以及确保正确base路径
    env:
      NODE_ENV: production # 确保使用正确的base路径配置

    steps:
      # 检出代码，获取完整历史以便正确处理内容
      - name: 检出仓库代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token
          persist-credentials: true # 保持凭证以便后续推送

      # 配置Git用户信息（用于gh-pages分支提交）
      - name: 配置Git用户
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 设置Node.js环境 - 使用Node.js 18
      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 安装pnpm
      - name: 设置pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      # 诊断工作目录
      - name: 检查工作目录
        run: |
          pwd
          ls -la
          echo "检查package.json是否存在:"
          ls -la package.json

      # 首先构建组件库
      - name: 构建组件库
        run: |
          pnpm install
          pnpm run lib
          ls -la lib || echo "lib目录不存在!"

      # 安装文档依赖并构建
      - name: 构建文档
        run: |
          # 确保所有依赖都已安装
          pnpm install
          # 构建文档
          pnpm run docs:build
          # 检查构建结果
          ls -la docs/.vitepress/dist || echo "构建目录不存在!"

      # 部署到GitHub Pages
      - name: 部署到gh-pages分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署的目标分支
          folder: docs/.vitepress/dist # VitePress构建输出目录
          clean: true # 在部署前清理旧文件
          commit-message: "docs: 自动部署文档 [skip ci]" # 自定义提交消息
          token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token

      # 部署完成通知
      - name: 部署完成
        run: echo "✅ 文档已成功部署到gh-pages分支"
